apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zing
spec:
  minReadySeconds: 5
  replicas: 2
  template:
    metadata:
      labels:
        name: zing
    spec:
      containers:
      - name: zing
        image: foot/zing:ewq
        args:
        - -msg=Ahoy
        ports:
        - containerPort: 80
