---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    flux.weave.works/tag.helloworld: regexp:master-[^a][^0][^0]
  name: helloworld
spec:
  minReadySeconds: 5
  replicas: 10
  template:
    metadata:
      labels:
        name: helloworld
    spec:
      containers:
      - name: helloworld
        image: quay.io/weaveworks/helloworld:master-07a1b6b
        args:
        - -msg=Ahoy
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 0
      - name: sidecar
        image: quay.io/weaveworks/sidecar:master-a000001
        args:
        - -addr=:8080
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 0
