---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.flux: glob:master-*
  name: weave-flux-agent
  namespace: weave
spec:
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  template:
    metadata:
      labels:
        name: weave-flux-agent
      annotations:
        prometheus.io.port: "3030"
    spec:
      volumes:
      - name: git-key
        secret:
          secretName: flux-git-key
          defaultMode: 0400
      # A tmpfs used for generating SSH keys
      - name: git-keygen
        emptyDir:
          medium: Memory
      - name: quay-secret
        secret:
          secretName: flux-quay-secret
      containers:
      - name: flux
        image: quay.io/weaveworks/flux:master-ecc34217
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3030
        volumeMounts:
        - name: git-key
          mountPath: /etc/fluxd/ssh
        - name: git-keygen
          mountPath: /var/fluxd/keygen # to match image's ~/.ssh/config and --ssh-keygen-dir below
        args:
        - --token=$(WEAVE_CLOUD_TOKEN)
        - --connect=wss://frontend.dev.weave.works/api/flux
        - --memcached-hostname=weave-flux-memcached.weave.svc.cluster.local
        - --git-ci-skip=true
        - --git-url=git@github.com:foot/flux-example
        - --git-path=hejworld-conf
        - --git-branch=master
        - --git-label=flux-lively-bird-80
        - --ssh-keygen-dir=/var/fluxd/ssh
        env:
        - name: WEAVE_CLOUD_TOKEN
          valueFrom:
            secretKeyRef:
              key: token
              name: weave-cloud
